"use strict";
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var mappers_1 = require("../models/mappers");
Object.defineProperty(exports, "UsageListResult", { enumerable: true, get: function () { return mappers_1.UsageListResult; } });
Object.defineProperty(exports, "Usage", { enumerable: true, get: function () { return mappers_1.Usage; } });
Object.defineProperty(exports, "UsageName", { enumerable: true, get: function () { return mappers_1.UsageName; } });
Object.defineProperty(exports, "CloudError", { enumerable: true, get: function () { return mappers_1.CloudError; } });
