"use strict";
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var mappers_1 = require("../models/mappers");
Object.defineProperty(exports, "ContainerGroupListResult", { enumerable: true, get: function () { return mappers_1.ContainerGroupListResult; } });
Object.defineProperty(exports, "ContainerGroup", { enumerable: true, get: function () { return mappers_1.ContainerGroup; } });
Object.defineProperty(exports, "Resource", { enumerable: true, get: function () { return mappers_1.Resource; } });
Object.defineProperty(exports, "BaseResource", { enumerable: true, get: function () { return mappers_1.BaseResource; } });
Object.defineProperty(exports, "ContainerGroupIdentity", { enumerable: true, get: function () { return mappers_1.ContainerGroupIdentity; } });
Object.defineProperty(exports, "ContainerGroupIdentityUserAssignedIdentitiesValue", { enumerable: true, get: function () { return mappers_1.ContainerGroupIdentityUserAssignedIdentitiesValue; } });
Object.defineProperty(exports, "Container", { enumerable: true, get: function () { return mappers_1.Container; } });
Object.defineProperty(exports, "ContainerPort", { enumerable: true, get: function () { return mappers_1.ContainerPort; } });
Object.defineProperty(exports, "EnvironmentVariable", { enumerable: true, get: function () { return mappers_1.EnvironmentVariable; } });
Object.defineProperty(exports, "ContainerPropertiesInstanceView", { enumerable: true, get: function () { return mappers_1.ContainerPropertiesInstanceView; } });
Object.defineProperty(exports, "ContainerState", { enumerable: true, get: function () { return mappers_1.ContainerState; } });
Object.defineProperty(exports, "Event", { enumerable: true, get: function () { return mappers_1.Event; } });
Object.defineProperty(exports, "ResourceRequirements", { enumerable: true, get: function () { return mappers_1.ResourceRequirements; } });
Object.defineProperty(exports, "ResourceRequests", { enumerable: true, get: function () { return mappers_1.ResourceRequests; } });
Object.defineProperty(exports, "GpuResource", { enumerable: true, get: function () { return mappers_1.GpuResource; } });
Object.defineProperty(exports, "ResourceLimits", { enumerable: true, get: function () { return mappers_1.ResourceLimits; } });
Object.defineProperty(exports, "VolumeMount", { enumerable: true, get: function () { return mappers_1.VolumeMount; } });
Object.defineProperty(exports, "ContainerProbe", { enumerable: true, get: function () { return mappers_1.ContainerProbe; } });
Object.defineProperty(exports, "ContainerExec", { enumerable: true, get: function () { return mappers_1.ContainerExec; } });
Object.defineProperty(exports, "ContainerHttpGet", { enumerable: true, get: function () { return mappers_1.ContainerHttpGet; } });
Object.defineProperty(exports, "ImageRegistryCredential", { enumerable: true, get: function () { return mappers_1.ImageRegistryCredential; } });
Object.defineProperty(exports, "IpAddress", { enumerable: true, get: function () { return mappers_1.IpAddress; } });
Object.defineProperty(exports, "Port", { enumerable: true, get: function () { return mappers_1.Port; } });
Object.defineProperty(exports, "Volume", { enumerable: true, get: function () { return mappers_1.Volume; } });
Object.defineProperty(exports, "AzureFileVolume", { enumerable: true, get: function () { return mappers_1.AzureFileVolume; } });
Object.defineProperty(exports, "GitRepoVolume", { enumerable: true, get: function () { return mappers_1.GitRepoVolume; } });
Object.defineProperty(exports, "ContainerGroupPropertiesInstanceView", { enumerable: true, get: function () { return mappers_1.ContainerGroupPropertiesInstanceView; } });
Object.defineProperty(exports, "ContainerGroupDiagnostics", { enumerable: true, get: function () { return mappers_1.ContainerGroupDiagnostics; } });
Object.defineProperty(exports, "LogAnalytics", { enumerable: true, get: function () { return mappers_1.LogAnalytics; } });
Object.defineProperty(exports, "ContainerGroupNetworkProfile", { enumerable: true, get: function () { return mappers_1.ContainerGroupNetworkProfile; } });
Object.defineProperty(exports, "DnsConfiguration", { enumerable: true, get: function () { return mappers_1.DnsConfiguration; } });
Object.defineProperty(exports, "CloudError", { enumerable: true, get: function () { return mappers_1.CloudError; } });
