"use strict";
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.virtualNetworkName = exports.tail = exports.subscriptionId = exports.subnetName = exports.resourceGroupName = exports.nextPageLink = exports.location = exports.containerName = exports.containerGroupName = exports.apiVersion = exports.acceptLanguage = void 0;
exports.acceptLanguage = {
    parameterPath: "acceptLanguage",
    mapper: {
        serializedName: "accept-language",
        defaultValue: 'en-US',
        type: {
            name: "String"
        }
    }
};
exports.apiVersion = {
    parameterPath: "apiVersion",
    mapper: {
        required: true,
        serializedName: "api-version",
        type: {
            name: "String"
        }
    }
};
exports.containerGroupName = {
    parameterPath: "containerGroupName",
    mapper: {
        required: true,
        serializedName: "containerGroupName",
        type: {
            name: "String"
        }
    }
};
exports.containerName = {
    parameterPath: "containerName",
    mapper: {
        required: true,
        serializedName: "containerName",
        type: {
            name: "String"
        }
    }
};
exports.location = {
    parameterPath: "location",
    mapper: {
        required: true,
        serializedName: "location",
        type: {
            name: "String"
        }
    }
};
exports.nextPageLink = {
    parameterPath: "nextPageLink",
    mapper: {
        required: true,
        serializedName: "nextLink",
        type: {
            name: "String"
        }
    },
    skipEncoding: true
};
exports.resourceGroupName = {
    parameterPath: "resourceGroupName",
    mapper: {
        required: true,
        serializedName: "resourceGroupName",
        type: {
            name: "String"
        }
    }
};
exports.subnetName = {
    parameterPath: "subnetName",
    mapper: {
        required: true,
        serializedName: "subnetName",
        type: {
            name: "String"
        }
    }
};
exports.subscriptionId = {
    parameterPath: "subscriptionId",
    mapper: {
        required: true,
        serializedName: "subscriptionId",
        type: {
            name: "String"
        }
    }
};
exports.tail = {
    parameterPath: [
        "options",
        "tail"
    ],
    mapper: {
        serializedName: "tail",
        type: {
            name: "Number"
        }
    }
};
exports.virtualNetworkName = {
    parameterPath: "virtualNetworkName",
    mapper: {
        required: true,
        serializedName: "virtualNetworkName",
        type: {
            name: "String"
        }
    }
};
